server:
  port: 8081

datasource:
  jdbc-url: "jdbc:mysql://118.26.39.88:3306/snailhouse?characterEncoding=utf8&useSSL=true"
  username: snailhouse
  password: "csc04217846688"
  driver-class-name: com.mysql.jdbc.Driver
  max-idle: 10
  max-wait: 10000
  min-idle: 5
  initial-size: 5
  continue-on-error: false
  test-on-borrow: true
  test-while-idle: true
  init-sql-path: classpath:db/*.sql

version:
  /v1/api

management:
  security:
    enabled: false
  context-path: /admin
  version: 1.0.1

mybatis:
  mapper-locations: "classpath*:com/channing/snailhouse/model/*Mapper.xml"
  type-aliases-package: com.channing.snailhouse.bean.dto

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql